name: Manual Checkout Workflow

on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest

    steps:
      - name: List files BEFORE checkout
        run: ls -a

      - name: Checkout repository manually
        run: |
          git init
          git remote add origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git fetch origin
          git checkout main

      - name: List files AFTER checkout
        run: ls -a
